name: CI Pipeline Tests Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manually triggering from the actions tab
  workflow_dispatch:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # Enable colour output for GTEST and XML file generation
  GTEST_COLOR: yes
  GTEST_OUTPUT: xml:test-results/

jobs:
  build:
    # The CMake configure and build commands are platform agnostic anda should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC 11
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{github.workspace}}/build/IPCTests/test-results/**/*.xml
      
